database:
  uri: "sqlite:///app.db"
  track_modifications: false

api_keys:
  openai_api_key: "sk-ii118tH08VLWdLka-KkMmHOg3-umNyTPbdqXh4mcPbT3BlbkFJnF24It0qH7SbvG_baWV0X1PMNVbGeeSJgFU8fjbzEA"
  gemini_api_key: "YOUR_GEMINI_API_KEY"
  anthropic_api_key: "YOUR_ANTHROPIC_API_KEY"
  hf_api_key: "YOUR_HF_API_KEY"


llm:
  openai:
    - "gpt-4o"
  anthropic:
    - "claude-2"
  hf:
    - "gpt2"
  gemini:
    - "gemini-1.5-pro"
  timeout: 60
  retries: 3
