database:
  file_name: "app.db"
  uri: "sqlite:///app.db"
  track_modifications: false

llm:
  openai:
    - "gpt-4o"
  anthropic:
    - "claude-3-5-sonnet-20240620"
  hf:
    - "meta-llama/Llama-3.1-70B-Instruct"
  gemini:
    - "gemini-1.5-pro"
  timeout: 60
  retries: 3

google-ai-platform:
  active: false # controls to use environment api key for Gemini or not.
  project: "lmcode"
  location: "us-central1"