database:
  uri: "sqlite:///app.db"
  track_modifications: false

api_keys:
  openai_api_key: "YOUR_OPENAI_API_KEY"
  gemini_api_key: "YOUR_GEMINI_API_KEY"
  anthropic_api_key: "YOUR_ANTHROPIC_API_KEY"
  hf_api_key: "YOUR_HUGGING_FACE_API_KEY"


llm:
  openai:
    - "gpt-4o"
  anthropic:
    - "claude-2"
  hf:
    - "deepseek-ai/DeepSeek-Coder-V2-Instruct"
    - "codellama/CodeLlama-34b-Instruct-hf"
  gemini:
    - "gemini-1.5-pro"
  timeout: 60
  retries: 3
