database:
  uri: "sqlite:///app.db"
  track_modifications: false

llm:
  openai:
    - "gpt-4o"
  anthropic:
    - "claude-2"
  hf:
    - "deepseek-ai/DeepSeek-Coder-V2-Instruct"
    - "codellama/CodeLlama-34b-Instruct-hf"
  gemini:
    - "gemini-1.5-pro"
  timeout: 60
  retries: 3
