instance:
  path: "instance"

database:
  file_name: "app.db"
  uri: "sqlite:///app.db"
  track_modifications: false

logging:
  file_name: "logfile.log"
  log_to_file: false # if false, logging to console

llm:
  openai:
    - id: "gpt-4o"
      name: "GPT-4o"
      max_tokens: 5000
  anthropic:
    - id: "claude-3-5-sonnet-20240620"
      name: "Claude-3.5-sonnet"
      max_tokens: 5000
  hf:
    - id: "meta-llama/Llama-3.1-70B-Instruct"
      name: "Llama-3.1"
      max_tokens: 5000
    - id: "Qwen/Qwen2.5-72B-Instruct"
      name: "Qwen2.5"
      max_tokens: 5000
  gemini:
    - id: "gemini-1.5-pro"
      name: "Gemini-1.5-pro"
      max_tokens: 5000
  timeout: 60
  retries: 3

google-ai-platform:
  active: false # controls to use environment api key for Gemini or not. False means use local Gemini Key; True means use Google AI Platform.
  project: "lmcode"
  location: "us-central1"


