database:
  uri: "sqlite:///app.db"
  track_modifications: false

llm:
  openai:
    - "gpt-4o"
  anthropic:
    - "claude-2"
  hf:
    - "meta-llama/Llama-3.1-70B-Instruct"
  gemini:
    - "gemini-1.5-pro"
  timeout: 60
  retries: 3
